# Generated by Django 4.0.3 on 2022-03-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamforcebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text_lemmas',
            field=models.TextField(verbose_name='Сообщение после лемматизации и нормализации'),
        ),
    ]
