# Generated by Django 4.0.3 on 2022-03-20 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamforcebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='teamforcebot.tag'),
        ),
    ]
