# Generated by Django 4.0.3 on 2022-03-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamforcebot', '0002_alter_message_text_lemmas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='tag',
        ),
        migrations.AddField(
            model_name='message',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='teamforcebot.tag'),
        ),
    ]
